/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eaio_stringsearch_ShiftOr */

#ifndef _Included_com_eaio_stringsearch_ShiftOr
#define _Included_com_eaio_stringsearch_ShiftOr
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eaio_stringsearch_ShiftOr_CROSSOVER_IBM_1_3
#define com_eaio_stringsearch_ShiftOr_CROSSOVER_IBM_1_3 68L
#undef com_eaio_stringsearch_ShiftOr_CROSSOVER_SUN_PRE_1_4
#define com_eaio_stringsearch_ShiftOr_CROSSOVER_SUN_PRE_1_4 90L
#undef com_eaio_stringsearch_ShiftOr_CROSSOVER_SUN_1_4
#define com_eaio_stringsearch_ShiftOr_CROSSOVER_SUN_1_4 12L
/* Inaccessible static: useNative */
/* Inaccessible static: crossover */
/* Inaccessible static: activeDispatch */
/*
 * Class:     com_eaio_stringsearch_ShiftOr
 * Method:    nativeSearchBytes
 * Signature: ([BII[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_eaio_stringsearch_ShiftOr_nativeSearchBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
